#include "protocolo.h"
#include <iostream>
#include <string>

int main()
{
        std::string input = "211JACALVCOMENTIRASSONTODASMENTIRASCOSASQUEDICELAGENTEDECIRQUEESTEAMORESPROHIBIDOQUETENGOCUARENTAYTUVEINTEQUEYOSOYOTONOENTUVIDAYTUERESDULCEPRIMAVERA";
//    std::string input = "375JOSPAUNITHOSEKEYSINCLUDEDTHEPLUGBOARDSETTINGSTHEFRENCHPASSEDTHEMATERIALTOTHEPOLESANDREJEWSKIUSEDSOMEOFTHATMATERIALANDTHEMESSAGETRAFFICINSEPTEMBERANDOCTOBERTOSOLVEFORTHEUNKNOWNROTORWIRINGTHOSEKEYSINCLUDEDTHEPLUGBOARDSETTINGSTHEFRENCHPASSEDTHEMATERIALTOTHEPOLESANDREJEWSKIUSEDSOMEOFTHATMATERIALANDTHEMESSAGETRAFFICINSEPTEMBERANDOCTOBERTOSOLVEFORTHEUNKNOWNROTORWIRINGTHOSEKEYSINCLUDEDTHEPLUGBOARDSETTINGSTHEFRENCHPASSEDTHEMATERIALTOTHEPOLESANDREJEWSKIUSEDSOMEOFTHATMATERIALANDTHEMESSAGETRAFFICINSEPTEMBERANDOCTOBERTOSOLVEFORTHEUNKNOWNROTORWIRING";
    //Cifrado
    Protocolo protosCifra;
    protosCifra.cifrado(input);


    std::string resultado;
    //Descifrado
    Protocolo protosDescifra;
    resultado = protosDescifra.descifrado("mensaje.txt");
    std::cout << resultado << std::endl;
}
